sonar.projectKey=DisSagligiBackend
sonar.working.directory=C:\\Users\\\u0130rem\\source\\repos\\DisSagligiTakipApp\\DisSagligiTakipApp.API\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=C:\\Users\\\u0130rem\\source\\repos\\DisSagligiTakipApp\\DisSagligiTakipApp.API
sonar.pullrequest.cache.basepath=C:\\Users\\\u0130rem\\source\\repos\\DisSagligiTakipApp\\DisSagligiTakipApp.API

79D0396F-5524-0D4A-86A2-40C27B568AFE.sonar.projectKey=DisSagligiBackend:79D0396F-5524-0D4A-86A2-40C27B568AFE
79D0396F-5524-0D4A-86A2-40C27B568AFE.sonar.projectName=DisSagligiTakipApp.API
79D0396F-5524-0D4A-86A2-40C27B568AFE.sonar.projectBaseDir=C:\\Users\\\u0130rem\\source\\repos\\DisSagligiTakipApp\\DisSagligiTakipApp.API
79D0396F-5524-0D4A-86A2-40C27B568AFE.sonar.sourceEncoding=utf-8
79D0396F-5524-0D4A-86A2-40C27B568AFE.sonar.tests=
79D0396F-5524-0D4A-86A2-40C27B568AFE.sonar.sources=\
"C:\\Users\\\u0130rem\\source\\repos\\DisSagligiTakipApp\\DisSagligiTakipApp.API\\Controllers\\ActivityController.cs",\
"C:\\Users\\\u0130rem\\source\\repos\\DisSagligiTakipApp\\DisSagligiTakipApp.API\\Controllers\\AuthController.cs",\
"C:\\Users\\\u0130rem\\source\\repos\\DisSagligiTakipApp\\DisSagligiTakipApp.API\\Controllers\\DailyRecordController.cs",\
"C:\\Users\\\u0130rem\\source\\repos\\DisSagligiTakipApp\\DisSagligiTakipApp.API\\Controllers\\GoalController.cs",\
"C:\\Users\\\u0130rem\\source\\repos\\DisSagligiTakipApp\\DisSagligiTakipApp.API\\Controllers\\NoteController.cs",\
"C:\\Users\\\u0130rem\\source\\repos\\DisSagligiTakipApp\\DisSagligiTakipApp.API\\Controllers\\ProfileController.cs",\
"C:\\Users\\\u0130rem\\source\\repos\\DisSagligiTakipApp\\DisSagligiTakipApp.API\\Controllers\\SuggestionController.cs",\
"C:\\Users\\\u0130rem\\source\\repos\\DisSagligiTakipApp\\DisSagligiTakipApp.API\\Program.cs",\
"C:\\Users\\\u0130rem\\source\\repos\\DisSagligiTakipApp\\DisSagligiTakipApp.API\\obj\\Debug\\net10.0\\DisSagligiTakipApp.API.GlobalUsings.g.cs",\
"C:\\Users\\\u0130rem\\source\\repos\\DisSagligiTakipApp\\DisSagligiTakipApp.API\\obj\\Debug\\net10.0\\.NETCoreApp,Version=v10.0.AssemblyAttributes.cs",\
"C:\\Users\\\u0130rem\\source\\repos\\DisSagligiTakipApp\\DisSagligiTakipApp.API\\obj\\Debug\\net10.0\\Sentry.Attributes.cs",\
"C:\\Users\\\u0130rem\\source\\repos\\DisSagligiTakipApp\\DisSagligiTakipApp.API\\obj\\Debug\\net10.0\\DisSagligiTakipApp.API.AssemblyInfo.cs",\
"C:\\Users\\\u0130rem\\source\\repos\\DisSagligiTakipApp\\DisSagligiTakipApp.API\\obj\\Debug\\net10.0\\DisSagligiTakipApp.API.MvcApplicationPartsAssemblyInfo.cs",\
"C:\\Users\\\u0130rem\\source\\repos\\DisSagligiTakipApp\\DisSagligiTakipApp.API\\appsettings.Development.json",\
"C:\\Users\\\u0130rem\\source\\repos\\DisSagligiTakipApp\\DisSagligiTakipApp.API\\appsettings.json",\
"C:\\Users\\\u0130rem\\source\\repos\\DisSagligiTakipApp\\DisSagligiTakipApp.API\\DisSagligiTakipApp.API.http",\
"C:\\Users\\\u0130rem\\source\\repos\\DisSagligiTakipApp\\DisSagligiTakipApp.API\\Properties\\launchSettings.json",\
"C:\\Users\\\u0130rem\\source\\repos\\DisSagligiTakipApp\\DisSagligiTakipApp.API\\obj\\DisSagligiTakipApp.API.csproj.nuget.dgspec.json",\
"C:\\Users\\\u0130rem\\source\\repos\\DisSagligiTakipApp\\DisSagligiTakipApp.API\\obj\\project.assets.json",\
"C:\\Users\\\u0130rem\\source\\repos\\DisSagligiTakipApp\\DisSagligiTakipApp.API\\bin\\Debug\\net10.0\\appsettings.Development.json",\
"C:\\Users\\\u0130rem\\source\\repos\\DisSagligiTakipApp\\DisSagligiTakipApp.API\\bin\\Debug\\net10.0\\appsettings.json",\
"C:\\Users\\\u0130rem\\source\\repos\\DisSagligiTakipApp\\DisSagligiTakipApp.API\\bin\\Debug\\net10.0\\DisSagligiTakipApp.API.deps.json",\
"C:\\Users\\\u0130rem\\source\\repos\\DisSagligiTakipApp\\DisSagligiTakipApp.API\\bin\\Debug\\net10.0\\DisSagligiTakipApp.API.runtimeconfig.json",\
"C:\\Users\\\u0130rem\\source\\repos\\DisSagligiTakipApp\\DisSagligiTakipApp.API\\bin\\Debug\\net10.0\\DisSagligiTakipApp.API.staticwebassets.endpoints.json",\
"C:\\Users\\\u0130rem\\source\\repos\\DisSagligiTakipApp\\DisSagligiTakipApp.API\\bin\\Debug\\net10.0\\DisSagligiTakipApp.API.staticwebassets.runtime.json",\
"C:\\Users\\\u0130rem\\source\\repos\\DisSagligiTakipApp\\DisSagligiTakipApp.API\\obj\\Debug\\net10.0\\DisSagligiTakipApp.API.sourcelink.json",\
"C:\\Users\\\u0130rem\\source\\repos\\DisSagligiTakipApp\\DisSagligiTakipApp.API\\obj\\Debug\\net10.0\\rjsmcshtml.dswa.cache.json",\
"C:\\Users\\\u0130rem\\source\\repos\\DisSagligiTakipApp\\DisSagligiTakipApp.API\\obj\\Debug\\net10.0\\rjsmrazor.dswa.cache.json",\
"C:\\Users\\\u0130rem\\source\\repos\\DisSagligiTakipApp\\DisSagligiTakipApp.API\\obj\\Debug\\net10.0\\rpswa.dswa.cache.json",\
"C:\\Users\\\u0130rem\\source\\repos\\DisSagligiTakipApp\\DisSagligiTakipApp.API\\obj\\Debug\\net10.0\\staticwebassets.build.endpoints.json",\
"C:\\Users\\\u0130rem\\source\\repos\\DisSagligiTakipApp\\DisSagligiTakipApp.API\\obj\\Debug\\net10.0\\staticwebassets.build.json",\
"C:\\Users\\\u0130rem\\source\\repos\\DisSagligiTakipApp\\DisSagligiTakipApp.API\\obj\\Debug\\net10.0\\staticwebassets.development.json",\
"C:\\Users\\\u0130rem\\source\\repos\\DisSagligiTakipApp\\DisSagligiTakipApp.API\\bin\\Debug\\net10.0\\BuildHost-netcore\\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.deps.json",\
"C:\\Users\\\u0130rem\\source\\repos\\DisSagligiTakipApp\\DisSagligiTakipApp.API\\bin\\Debug\\net10.0\\BuildHost-netcore\\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.runtimeconfig.json"

79D0396F-5524-0D4A-86A2-40C27B568AFE.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\\u0130rem\\source\\repos\\DisSagligiTakipApp\\DisSagligiTakipApp.API\\.sonarqube\\out\\3"
79D0396F-5524-0D4A-86A2-40C27B568AFE.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\\u0130rem\\source\\repos\\DisSagligiTakipApp\\DisSagligiTakipApp.API\\.sonarqube\\out\\3\\Issues.json"
79D0396F-5524-0D4A-86A2-40C27B568AFE.sonar.cs.scanner.telemetry=\
"C:\\Users\\\u0130rem\\source\\repos\\DisSagligiTakipApp\\DisSagligiTakipApp.API\\.sonarqube\\out\\3\\Telemetry.json"

79D0396F-5524-0D4A-86A2-40C27B568AFE.sonar.working.directory=C:\\Users\\\u0130rem\\source\\repos\\DisSagligiTakipApp\\DisSagligiTakipApp.API\\.sonarqube\\out\\.sonar\\mod0
sonar.host.url=http://localhost:9000
sonar.visualstudio.enable=false

sonar.modules=79D0396F-5524-0D4A-86A2-40C27B568AFE

