// <auto-generated />
using System;
using DisSagligiTakipApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DisSagligiTakipApp.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260317132752_AddDailyRecords")]
    partial class AddDailyRecords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DisSagligiTakipApp.Core.Entities.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("GoalId")
                        .HasColumnType("int");

                    b.Property<bool>("IsApplied")
                        .HasColumnType("bit");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GoalId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("DisSagligiTakipApp.Core.Entities.DailyRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrushCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Flossed")
                        .HasColumnType("bit");

                    b.Property<bool>("Mouthwash")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date")
                        .IsUnique();

                    b.ToTable("DailyRecords");
                });

            modelBuilder.Entity("DisSagligiTakipApp.Core.Entities.Goal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("DisSagligiTakipApp.Core.Entities.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("DisSagligiTakipApp.Core.Entities.Suggestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Suggestions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Text = "Dişlerinizi günde en az 2 kez, 2'şer dakika boyunca fırçalayın."
                        },
                        new
                        {
                            Id = 2,
                            Text = "Diş ipi kullanmak, diş fırçasının ulaşamadığı yerlerin %35'ini temizler."
                        },
                        new
                        {
                            Id = 3,
                            Text = "Şekerli içecekler tüketimini azaltmak diş çürümesini önemli ölçüde engeller."
                        },
                        new
                        {
                            Id = 4,
                            Text = "Gece yatmadan önce dişlerinizi fırçalamak, gece boyunca bakteri oluşumunu azaltır."
                        },
                        new
                        {
                            Id = 5,
                            Text = "Diş fırçanızı her 3 ayda bir yenilemeyi unutmayın."
                        },
                        new
                        {
                            Id = 6,
                            Text = "Meyve suyu yerine taze meyve tüketmek dişleri asit hasarından korur."
                        },
                        new
                        {
                            Id = 7,
                            Text = "Florürlü diş macunu kullanmak diş minесini güçlendirir."
                        },
                        new
                        {
                            Id = 8,
                            Text = "Ağız gargarası kullanmak, fırçalamanın ulaşamadığı bölgelerdeki bakterileri temizler."
                        },
                        new
                        {
                            Id = 9,
                            Text = "Düzenli diş hekimi kontrolleri erken dönem problemlerin tespitini sağlar."
                        },
                        new
                        {
                            Id = 10,
                            Text = "Su içmek ağız kuruluğunu önler ve asit dengesini korur."
                        },
                        new
                        {
                            Id = 11,
                            Text = "Asitli içeceklerden sonra en az 30 dakika bekleyip dişlerinizi fırçalayın."
                        },
                        new
                        {
                            Id = 12,
                            Text = "Diş gıcırdatma (bruksizm) varsa diş hekiminizden gece koruyucusu isteyin."
                        });
                });

            modelBuilder.Entity("DisSagligiTakipApp.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DisSagligiTakipApp.Core.Entities.Activity", b =>
                {
                    b.HasOne("DisSagligiTakipApp.Core.Entities.Goal", "Goal")
                        .WithMany()
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("DisSagligiTakipApp.Core.Entities.DailyRecord", b =>
                {
                    b.HasOne("DisSagligiTakipApp.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DisSagligiTakipApp.Core.Entities.Goal", b =>
                {
                    b.HasOne("DisSagligiTakipApp.Core.Entities.User", "User")
                        .WithMany("Goals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DisSagligiTakipApp.Core.Entities.Note", b =>
                {
                    b.HasOne("DisSagligiTakipApp.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DisSagligiTakipApp.Core.Entities.User", b =>
                {
                    b.Navigation("Goals");
                });
#pragma warning restore 612, 618
        }
    }
}
